title: Gökhan Aydın blog sayfası
email: g d-o-t gokhanaydin.net
description: >- #hello
baseurl: ""
url: ""
twitter_username: soraouji
github_username: soraouji

theme: minima
plugins:
  - jeykll-feed
