title: Gökhan Aydın blog sayfası
email: g d-o-t gokhanaydin.net
description: >- #hello
  merhabalar yeni dünya
baseurl: ""
url: ""
strapline: jekyll blog sitesi 

twitter_username: soraouji
github_username: soraouji
skills:
  - "Executive Producer"
  - "Graphic Designer"
  - "2d & 3d Animator"

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-admin
